# Generated by Django 2.0 on 2019-01-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
