# Generated by Django 2.0 on 2019-03-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='watch_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
