# Generated by Django 2.0 on 2018-12-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='null', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='null', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
