# Generated by Django 2.0 on 2018-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameEvents', '0003_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('En Espera', 'EN_ESPERA'), ('En Juego', 'EN_JUEGO'), ('Terminado', 'TERMINADO')], default='En Espera', max_length=30),
        ),
    ]
