# Generated by Django 2.0 on 2018-12-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='slug',
            field=models.SlugField(default='slug-default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamer',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
