# Generated by Django 2.0 on 2019-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_list_last_update'),
        ('wiki', '0002_team_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='website',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='website',
        ),
        migrations.AddField(
            model_name='gamer',
            name='social_urls',
            field=models.ManyToManyField(blank=True, related_name='_gamer_social_urls_+', to='blog.socialURL'),
        ),
        migrations.AddField(
            model_name='team',
            name='social_urls',
            field=models.ManyToManyField(blank=True, related_name='_team_social_urls_+', to='blog.socialURL'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='social_urls',
            field=models.ManyToManyField(blank=True, related_name='_videogame_social_urls_+', to='blog.socialURL'),
        ),
    ]
