# Generated by Django 2.0 on 2018-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20181217_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
