# Generated by Django 2.0 on 2019-03-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20190318_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wiki.Team'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='videogames',
            field=models.ManyToManyField(related_name='_gamer_videogames_+', to='wiki.VideoGame'),
        ),
        migrations.AlterField(
            model_name='team',
            name='videogames',
            field=models.ManyToManyField(related_name='_team_videogames_+', to='wiki.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='launch',
            field=models.DateField(blank=True, null=True),
        ),
    ]
