# Generated by Django 2.0 on 2018-12-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='subject',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
