# Generated by Django 2.0 on 2019-03-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_profile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='last_update',
        ),
    ]
