# Generated by Django 2.0 on 2018-12-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameEvents', '0002_auto_20181213_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('EN_JUEGO', 'En Juego'), ('TERMINADO', 'Terminado')], default='EN_ESPERA', max_length=30),
        ),
    ]
