# Generated by Django 2.0 on 2018-12-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('gameEvents', '0004_auto_20181214_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='games', to='wiki.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='videogame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='wiki.VideoGame'),
        ),
    ]
